CREATE TABLE IF NOT EXISTS `COUNTRIES` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(2) NOT NULL,
  `TAX` double NOT NULL,
  `CURRENCY` varchar(50) NOT NULL,
  `SYMBOL` varchar(5) DEFAULT NULL,
  `SHORT_CURRENCY` varchar(10) NOT NULL,
  PRIMARY KEY (`ID`)
);